"""initial schema

Revision ID: 849600a68f77
Revises: 
Create Date: 2026-09-28 17:12:06.440148
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '849600a68f77'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_user_username'))
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_category_slug'))
    )
    op.create_table('import_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upstream_commit', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_run'))
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('upstream_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_text', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_zh', sa.Text(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('prompt_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('overridden_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_case_category_id_category'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case')),
    sa.UniqueConstraint('category_id', 'upstream_no', name=op.f('uq_case_category_id'))
    )
    op.create_index(op.f('ix_case_category_id'), 'case', ['category_id'], unique=False)
    op.create_index(op.f('ix_case_status'), 'case', ['status'], unique=False)
    op.create_table('case_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('dominant_color', sa.String(length=7), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_case_image_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_image'))
    )
    op.create_index(op.f('ix_case_image_case_id'), 'case_image', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_image_sha256'), 'case_image', ['sha256'], unique=False)
    op.create_table('case_tag',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_case_tag_case_id_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_case_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'tag_id', name=op.f('pk_case_tag'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_tag')
    op.drop_index(op.f('ix_case_image_sha256'), table_name='case_image')
    op.drop_index(op.f('ix_case_image_case_id'), table_name='case_image')
    op.drop_table('case_image')
    op.drop_index(op.f('ix_case_status'), table_name='case')
    op.drop_index(op.f('ix_case_category_id'), table_name='case')
    op.drop_table('case')
    op.drop_table('tag')
    op.drop_table('import_run')
    op.drop_table('category')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
